const orders=[{
    "orderId":"0001",
    "status":[
            {
                "statusCode":"Delivered",
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc3"}
            }
        ],
    "products":[
            {
                "name":"jeans",
                "quantity":5,
                "serviseTypes":[],
                "price":450,
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc4"}
            }
        ],
    "subtotal":300,
    "pickupCharge":90,
    "total":390,
    "dateTime":"2021-11-02T14:00:00.756Z",
    "deliveryAddress":{
            "streetAddress":"1-8/567  appt dilsukhnagar",
            "state":"Telangana",
            "district":"Hyderabad",
            "pincode":500060
        },
    "storeAddress":{
        "location":"Hyderabad",
        "address":"1-85/45 street lbnagar",
        "phone":9999999,
        "district":"Hyderabad",
        "state":"Telangana"
        },
    "__v":0
},
{
    "orderId":"0002",
    "status":[
            {
                "statusCode":"Delivered",
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc3"}
            }
        ],
    "products":[
            {
                "name":"jeans",
                "quantity":5,
                "serviseTypes":[],
                "price":450,
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc4"}
            }
        ],
    "subtotal":300,
    "pickupCharge":90,
    "total":390,
    "dateTime":"2021-11-02T14:00:00.756Z",
    "deliveryAddress":{
            "streetAddress":"1-8/567  appt dilsukhnagar",
            "state":"Telangana",
            "district":"Hyderabad",
            "pincode":500060
        },
    "storeAddress":{
        "location":"Hyderabad",
        "address":"1-85/45 street lbnagar",
        "phone":9999999,
        "district":"Hyderabad",
        "state":"Telangana"
        },
    "__v":0
},
{
    "orderId":"0003",
    "status":[
            {
                "statusCode":"Delivered",
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc3"}
            }
        ],
    "products":[
            {
                "name":"jeans",
                "quantity":5,
                "serviseTypes":[],
                "price":450,
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc4"}
            }
        ],
    "subtotal":300,
    "pickupCharge":90,
    "total":390,
    "dateTime":"2021-11-02T14:00:00.756Z",
    "deliveryAddress":{
            "streetAddress":"1-8/567  appt dilsukhnagar",
            "state":"Telangana",
            "district":"Hyderabad",
            "pincode":500060
        },
    "storeAddress":{
        "location":"Hyderabad",
        "address":"1-85/45 street lbnagar",
        "phone":9999999,
        "district":"Hyderabad",
        "state":"Telangana"
        },
    "__v":0
},
{
    "orderId":"0004",
    "status":[
            {
                "statusCode":"Delivered",
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc3"}
            }
        ],
    "products":[
            {
                "name":"jeans",
                "quantity":5,
                "serviseTypes":[],
                "price":450,
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc4"}
            }
        ],
    "subtotal":300,
    "pickupCharge":90,
    "total":390,
    "dateTime":"2021-11-02T14:00:00.756Z",
    "deliveryAddress":{
            "streetAddress":"1-8/567  appt dilsukhnagar",
            "state":"Telangana",
            "district":"Hyderabad",
            "pincode":500060
        },
    "storeAddress":{
        "location":"Hyderabad",
        "address":"1-85/45 street lbnagar",
        "phone":9999999,
        "district":"Hyderabad",
        "state":"Telangana"
        },
    "__v":0
},{
    "orderId":"0005",
    "status":[
            {
                "statusCode":"Delivered",
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc3"}
            }
        ],
    "products":[
            {
                "name":"jeans",
                "quantity":5,
                "serviseTypes":[],
                "price":450,
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc4"}
            }
        ],
    "subtotal":300,
    "pickupCharge":90,
    "total":390,
    "dateTime":"2021-11-02T14:00:00.756Z",
    "deliveryAddress":{
            "streetAddress":"1-8/567  appt dilsukhnagar",
            "state":"Telangana",
            "district":"Hyderabad",
            "pincode":500060
        },
    "storeAddress":{
        "location":"Hyderabad",
        "address":"1-85/45 street lbnagar",
        "phone":9999999,
        "district":"Hyderabad",
        "state":"Telangana"
        },
    "__v":0
},
{
    "orderId":"0006",
    "status":[
            {
                "statusCode":"Delivered",
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc3"}
            }
        ],
    "products":[
            {
                "name":"jeans",
                "quantity":5,
                "serviseTypes":[],
                "price":450,
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc4"}
            }
        ],
    "subtotal":300,
    "pickupCharge":90,
    "total":390,
    "dateTime":"2021-11-02T14:00:00.756Z",
    "deliveryAddress":{
            "streetAddress":"1-8/567  appt dilsukhnagar",
            "state":"Telangana",
            "district":"Hyderabad",
            "pincode":500060
        },
    "storeAddress":{
        "location":"Hyderabad",
        "address":"1-85/45 streetlbnagar",
        "phone":9999999,
        "district":"Hyderabad",
        "state":"Telangana"
        },
    "__v":0
},
{
    "orderId":"0007",
    "status":[
            {
                "statusCode":"Delivered",
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc3"}
            }
        ],
    "products":[
            {
                "name":"jeans",
                "quantity":5,
                "serviseTypes":[],
                "price":450,
                "_id":{"$oid":"617ffb5abf998adcb2f1dcc4"}
            }
        ],
    "subtotal":300,
    "pickupCharge":90,
    "total":390,
    "dateTime":"2021-11-02T14:00:00.756Z",
    "deliveryAddress":{
            "streetAddress":"1-8/567  appt dilsukhnagar",
            "state":"Telangana",
            "district":"Hyderabad",
            "pincode":500060
        },
    "storeAddress":{
        "location":"Hyderabad",
        "address":"1-85/45 street lbnagar",
        "phone":9999999,
        "district":"Hyderabad",
        "state":"Telangana"
        },
    "__v":0
},


]
export default orders;